
version: "3.9"
# docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ifx
      POSTGRES_PASSWORD: ifx
      POSTGRES_DB: ifx
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports: ["8080:8080"]

volumes:
  pgdata:
